### ISSUE TITLE
Dragons Lair TV Show Singe 1 meta data missing

### ISSUE THREAD

**Issue by tosca07** [DirtBagXon/hypseus_singe_data#1]
Hi DirtBagXon,
first of all thanks your for your amazing work on Daphne, singe and sing2 - really quite impressive (especially on the RaspberryPi).
Do you have meta data for the community singe 1 game Dragons Lair TV Show which you could add to your repository?
Thanks a lot....

**Comment by DirtBagXon** [comment]
Unfortunately the video is way too long on that title, it exceeds the 65535 video frame limit of the Daphne VLDP.

That's strictly **Singe 2** I'm afraid.

**Comment by DirtBagXon** [comment]
I am going to reopen this ticket, in an upcoming release Hypseus Singe will allow Dragons Lair TV, and other extended Singe 2 games to be supported.

**Comment by DirtBagXon** [comment]
I am going to reopen this ticket.

In an upcoming release, Hypseus Singe will allow Dragons Lair TV, and other extended Singe 2 games to be supported.

**Comment by DirtBagXon** [comment]
Fixed in https://github.com/DirtBagXon/hypseus_singe_data/commit/e1c1f985def86195189324673434875617f2482d
