### ISSUE TITLE
Missing FRAMEINFO.md

### ISSUE THREAD

**Issue by garygan89** [DirtBagXon/hypseus_singe_data#10]
Hmm I couldn't seems to find any `FRAMEINFO.md` file inside `singe2` folder for each game. I reckon this is needed to check against the video file to make sure the frame number matches.

**Comment by garygan89** [comment]
Turned out that only some folders don't have it, e.g. hayate.

**Comment by DirtBagXon** [comment]
If there isn't a `FRAMEINFO.md` just use the standard `ffmpeg` instructions. There are no real alternate videos for many of these games so it isn't necessary.

```
ffmpeg -i game.mp4 -an -qscale:v 4 -b:v 6000k -vf tpad=stop_mode=clone:stop_duration=2 -codec:v mpeg2video game.m2v
```

If you ever want clarification, pop onto Discord for confirmations from other users.

**Comment by Bladescatercanada** [comment]
> Hmm I couldn't seems to find any `FRAMEINFO.md` file inside `singe2` folder for each game. I reckon this is needed to check against the video file to make sure the frame number matches.
to display the number of frames you can add this code in your addon.singe file or in your my game.singe file
bShowFrame = true
then when you play if you pause you will have the frame number displayed in large letters on the pause screen
but if you simply want to edit your movements with the frame number use the file in mp4 format directly with quicktime player (free) right click on the time displayed and select frame
or use adobe premiere (paid)

**Comment by DirtBagXon** [comment]
Closing this down as it's been hanging around for some time and the answer is to check-in via Discord these days.
