### ISSUE TITLE
porting mononoke?

### ISSUE THREAD

**Issue by zanac** [DirtBagXon/hypseus_singe_data#3]
Hi, i found "mononoke" here.... how can we port it? http://www.emuline.org/topic/1628-arcade-pc-daphne-singe-singe-2-set-hypseus-singe-laser-disc/

**Comment by DirtBagXon** [comment]
https://github.com/DirtBagXon/hypseus_singe_data#these-singe-2-games-have-known-issues

Unfortunately, this game exceeds the 16-bit **65535** video frames limit - It's **Singe 2** only.
