### ISSUE TITLE
Missing "Framework" folder

### ISSUE THREAD

**Issue by Giandj** [DirtBagXon/hypseus_singe_data#9]
HI DirtBagxon , I think you miss to upload the "Framework" folder under:
/00-singe2/Sugar_Rush/Framework

A question:
Why this function (used in "globals.singe") in some Singe Games like "StarshipTroopers" is not recognised by compiler ?

setOverlayResolution (1280,720) --->>>error you try to assign a nil value

and also this function is not recognised (compiler error): 
setOverlaySize(BASEOVERLAY) --->>>error you try to assign a nil value

what is the correct function to set the Overlay Resolution / and Size ?

**Comment by DirtBagXon** [comment]
---

The `Framework` folder is not placed within the game subfolders, it placed alongside them.

 i.e.:

```
singe/Framework
singe/StarshipTroopers
singe/Sugar_Rush
```

The `Framework` folder is in the repo here:

https://github.com/DirtBagXon/hypseus_singe_data/tree/master/00-singe2/Framework

This is similar to the recent Singe 2 game layout.

---

The functions `setOverlayResolution` and `setOverlaySize` are only within version `2.10.4` of Hypseus Singe.

You will need to update to the latest version of Hypseus for the latest generation of games.

---

**Comment by DirtBagXon** [comment]
---

The `Framework` folder is not placed **within** the game subfolders, it is placed **alongside** them.

 i.e.:

```
singe/Framework
singe/StarshipTroopers
singe/Sugar_Rush
```

The `Framework` folder is located in the repo here:

https://github.com/DirtBagXon/hypseus_singe_data/tree/master/00-singe2/Framework

This is similar to the recent Singe 2 game layout.

---

The functions `setOverlayResolution` and `setOverlaySize` are only within version `2.10.4` of Hypseus Singe.

You will need to update to the latest version of Hypseus for the latest generation of games.

---

**Comment by DirtBagXon** [comment]
---

The `Framework` folder is not placed **within** the game subfolders, it is placed **alongside** them.

 _i.e._

```
singe/Framework
singe/StarshipTroopers
singe/Sugar_Rush
```

The `Framework` folder is located in the repo here:

https://github.com/DirtBagXon/hypseus_singe_data/tree/master/00-singe2/Framework

This is similar to the recent Singe 2 game layout.

---

The functions `setOverlayResolution` and `setOverlaySize` are only within version `2.10.4` of Hypseus Singe.

You will need to update to the latest version of Hypseus for the latest generation of games.

---

**Comment by Giandj** [comment]
All clear, thank you for support.
I have also converted all the new games (running on latest version of Singe 2.04) to old Singe 2 (earlier) version...(It's a downgrade !!!) ..
Yes but works..
So all new games (like Venus Wars, and so on) can (now) run under old Singe 2 version, skipping compiler errors...(maybe one day i will install the latest Singe 2.04 version on raspberrypi)

Thank you

**Comment by DirtBagXon** [comment]
Glad it's all working.

_"(maybe one day i will install the latest Singe 2.10.4 version on raspberrypi)"_

The source is very simple to compile on the Pi, see [here](https://github.com/DirtBagXon/hypseus-singe/blob/master/src/3rdparty/retropie/RETROPIE.md#install-hypseus-singe). Unless you have other reasons to not upgrade...
